export * from './create-b2b-student.schema';
export * from './create-b2c-student.schema';
export * from './delete-student.schema';
export * from './student.schema';
export * from './students.schema';
export * from './total-students.schema';
export * from './update-b2b-student.schema';
export * from './update-b2c-student.schema';
export * from '../../business/schemas/student-pitch-script.schema';
